# Data Collection

In [1]:
# Your code here - remember to use markdown cells for comments as well!
#2015-2016
#2016-2017
#2017-2018
#2018-2019

import pandas as pd
import re
import requests
from nba_stats_tracking import tracking
import time


df = pd.read_csv('2017-2018_player_per100poss.csv')
df2 = pd.read_csv('2017-2018_player_adv.csv')
df3 = pd.read_csv('2017-2018_player_shooting_stats.csv', header = [0, 1])

In [2]:
df.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,Unnamed: 29,ORtg,DRtg
0,1,Álex Abrines\abrinal01,SG,24,OKC,75,8,1134,5.0,12.7,...,5.0,1.2,1.7,0.4,1.1,5.4,15.4,NaN,116.0,110
1,2,Quincy Acy\acyqu01,PF,27,BRK,70,8,1359,4.6,13.0,...,9.2,2.0,1.2,1.0,2.1,5.3,14.7,NaN,99.0,110
2,3,Steven Adams\adamsst01,C,24,OKC,76,76,2487,8.9,14.2,...,13.7,1.8,1.8,1.6,2.6,4.3,21.1,NaN,125.0,107
3,4,Bam Adebayo\adebaba01,C,20,MIA,69,19,1368,6.4,12.5,...,14.0,3.7,1.2,1.5,2.4,5.1,17.5,NaN,116.0,105
4,5,Arron Afflalo\afflaar01,SG,32,ORL,53,3,682,4.7,11.6,...,4.7,2.2,0.3,0.6,1.5,4.0,12.8,NaN,98.0,115

In [3]:
df.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Unnamed: 29',
       'ORtg', 'DRtg'],
      dtype='object')

In [4]:
df2.head()

,Rk,Player,Pos,Age,Tm,G,MP,PER,TS%,3PAr,...,Unnamed: 19,OWS,DWS,WS,WS/48,Unnamed: 24,OBPM,DBPM,BPM,VORP
0,1,Álex Abrines\abrinal01,SG,24,OKC,75,1134,9.0,0.567,0.759,...,NaN,1.3,1.0,2.2,0.094,NaN,-1.9,0.4,-1.5,0.1
1,2,Quincy Acy\acyqu01,PF,27,BRK,70,1359,8.2,0.525,0.800,...,NaN,-0.1,1.1,1.0,0.036,NaN,-2.6,0.1,-2.5,-0.2
2,3,Steven Adams\adamsst01,C,24,OKC,76,2487,20.6,0.630,0.003,...,NaN,6.7,3.0,9.7,0.187,NaN,1.7,-0.6,1.1,2.0
3,4,Bam Adebayo\adebaba01,C,20,MIA,69,1368,15.7,0.570,0.021,...,NaN,2.3,1.9,4.2,0.148,NaN,-1.1,0.7,-0.4,0.6
4,5,Arron Afflalo\afflaar01,SG,32,ORL,53,682,5.8,0.516,0.432,...,NaN,-0.1,0.2,0.1,0.009,NaN,-3.8,-1.5,-5.4,-0.6

In [5]:
df2.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 'PER', 'TS%', '3PAr',
       'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%',
       'Unnamed: 19', 'OWS', 'DWS', 'WS', 'WS/48', 'Unnamed: 24', 'OBPM',
       'DBPM', 'BPM', 'VORP'],
      dtype='object')

In [6]:
df3.head()

  Unnamed: 0_level_0       Unnamed: 1_level_0 Unnamed: 2_level_0  \
                  Rk                   Player                Pos
0                  1   Álex Abrines\abrinal01                 SG
1                  2       Quincy Acy\acyqu01                 PF
2                  3   Steven Adams\adamsst01                  C
3                  4    Bam Adebayo\adebaba01                  C
4                  5  Arron Afflalo\afflaar01                 SG

  Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
                 Age                 Tm                  G                 MP
0                 24                OKC                 75               1134
1                 27                BRK                 70               1359
2                 24                OKC                 76               2487
3                 20                MIA                 69               1368
4                 32                ORL                 53                682

  Unnamed: 7_level_0 Unnamed: 8_level_0 Unnamed: 9_level_0  ... % of FG Ast'd  \
                 FG%              Dist. Unnamed: 9_level_1  ...            3P
0              0.395               20.3                NaN  ...         1.000
1              0.356               20.7                NaN  ...         0.990
2              0.629                2.6                NaN  ...           NaN
3              0.512                4.3                NaN  ...           NaN
4              0.401               17.1                NaN  ...         0.926

  Unnamed: 26_level_0  Dunks      Unnamed: 29_level_0 Corner 3s         \
  Unnamed: 26_level_1   %FGA    # Unnamed: 29_level_1      %3PA    3P%
0                 NaN  0.034    9                 NaN     0.253  0.375
1                 NaN  0.036    9                 NaN     0.305  0.404
2                 NaN  0.242  150                 NaN     0.000    NaN
3                 NaN  0.294   91                 NaN     0.000    NaN
4                 NaN  0.000    0                 NaN     0.414  0.276

  Unnamed: 32_level_0 Heaves
  Unnamed: 32_level_1   Att.  #
0                 NaN      1  0
1                 NaN      0  0
2                 NaN      2  0
3                 NaN      4  0
4                 NaN      0  0

[5 rows x 35 columns]

In [7]:
df3.columns

MultiIndex([(  'Unnamed: 0_level_0',                  'Rk'),
            (  'Unnamed: 1_level_0',              'Player'),
            (  'Unnamed: 2_level_0',                 'Pos'),
            (  'Unnamed: 3_level_0',                 'Age'),
            (  'Unnamed: 4_level_0',                  'Tm'),
            (  'Unnamed: 5_level_0',                   'G'),
            (  'Unnamed: 6_level_0',                  'MP'),
            (  'Unnamed: 7_level_0',                 'FG%'),
            (  'Unnamed: 8_level_0',               'Dist.'),
            (  'Unnamed: 9_level_0',  'Unnamed: 9_level_1'),
            ('% of FGA by Distance',                  '2P'),
            ('% of FGA by Distance',                 '0-3'),
            ('% of FGA by Distance',                '3-10'),
            ('% of FGA by Distance',               '10-16'),
            ('% of FGA by Distance',               '16-3P'),
            ('% of FGA by Distance',                  '3P'),
            ( 'Unnamed: 16_level_0', 'Unnamed: 16_level_1'),
            (     'FG% by Distance',                  '2P'),
            (     'FG% by Distance',                 '0-3'),
            (     'FG% by Distance',                '3-10'),
            (     'FG% by Distance',               '10-16'),
            (     'FG% by Distance',               '16-3P'),
            (     'FG% by Distance',                  '3P'),
            ( 'Unnamed: 23_level_0', 'Unnamed: 23_level_1'),
            (       '% of FG Ast'd',                  '2P'),
            (       '% of FG Ast'd',                  '3P'),
            ( 'Unnamed: 26_level_0', 'Unnamed: 26_level_1'),
            (               'Dunks',                '%FGA'),
            (               'Dunks',                   '#'),
            ( 'Unnamed: 29_level_0', 'Unnamed: 29_level_1'),
            (           'Corner 3s',                '%3PA'),
            (           'Corner 3s',                 '3P%'),
            ( 'Unnamed: 32_level_0', 'Unnamed: 32_level_1'),
            (              'Heaves',                'Att.'),
            (              'Heaves',                   '#')],
           )

In [8]:
#Creating functions to perform simple, preliminary cleaning
def reformat_standard_stats(dataframe):
    """Takes in a dataframe of player stats from Basketball Reference(either per game or per 100 possessions) 
    and removes columns that will not be necessary for data analysis or modeling."""
    df_new = dataframe.drop(columns=['Rk', 'Unnamed: 29']) #remove unncessary columns not relevant to EDA
    
    return df_new

def reformat_adv_stats(dataframe):
    """Takes in a dataframe of advanced player stats from Basketball Reference and removes columns that 
    will not be necessary for data analysis or modeling. We will also drop columns that are common with
    columns in the standard statistics dataframe."""
    df_new = dataframe.drop(columns=['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'MP', 
                                     'Unnamed: 19', 'Unnamed: 24'])
    
    return df_new

In [9]:
def join_dataframes(stand_df, adv_df, shooting_stats_df):
    """Joins standard and advanced dataframes from Basketball Reference into a singular dataframes.  Appends 
    selected columns from the shooting statistics dataframe.
    
    stand_df: A dataframe with standard player statistics from Basketball Reference. For example see this
    website: https://www.basketball-reference.com/leagues/NBA_2018_per_poss.html
    
    adv_df: A dataframe with advanced player statistics from Basketball Reference. For example see this 
    website: https://www.basketball-reference.com/leagues/NBA_2018_advanced.html
    
    shooting_stats_df: A dataframe with player shooting statistics from Basketball Reference. For example
    see this website: https://www.basketball-reference.com/leagues/NBA_2018_shooting.html
    
    year_range: The year range for an NBA season."""
    
    df_std_reformat = reformat_standard_stats(stand_df)
    df_adv_reformat = reformat_adv_stats(adv_df)
    
    df_joined_two = df_std_reformat.join(df_adv_reformat) #join standard and advanced player stats dataframes
    
    #creating new columns with data from shooting statistics dataframe
    df_joined_two['pct_of_FGA_twos'] = shooting_stats_df['% of FGA by Distance']['2P']
    df_joined_two['pct_of_FGA_threes'] = shooting_stats_df['% of FGA by Distance']['3P']
    df_joined_two['two_pt_fg_pct'] = shooting_stats_df['FG% by Distance']['2P']
    df_joined_two['three_pt_fg_pct'] = shooting_stats_df['FG% by Distance']['3P']
    
    df_final = df_joined_two
    
    return df_final

In [10]:
#check to make sure dataframes from the same year are the same length before running functions
len(df) == len(df2) == len(df3)

True

In [11]:
bballref_1718_df = join_dataframes(df, df2, df3)
bballref_1718_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 54 columns):
Player               664 non-null object
Pos                  664 non-null object
Age                  664 non-null int64
Tm                   664 non-null object
G                    664 non-null int64
GS                   664 non-null int64
MP                   664 non-null int64
FG                   664 non-null float64
FGA                  664 non-null float64
FG%                  660 non-null float64
3P                   664 non-null float64
3PA                  664 non-null float64
3P%                  599 non-null float64
2P                   664 non-null float64
2PA                  664 non-null float64
2P%                  646 non-null float64
FT                   664 non-null float64
FTA                  664 non-null float64
FT%                  606 non-null float64
ORB                  664 non-null float64
DRB                  664 non-null float64
TRB                  664 non-null float64
AST                  664 non-null float64
STL                  664 non-null float64
BLK                  664 non-null float64
TOV                  664 non-null float64
PF                   664 non-null float64
PTS                  664 non-null float64
ORtg                 662 non-null float64
DRtg                 664 non-null int64
PER                  664 non-null float64
TS%                  660 non-null float64
3PAr                 660 non-null float64
FTr                  660 non-null float64
ORB%                 664 non-null float64
DRB%                 664 non-null float64
TRB%                 664 non-null float64
AST%                 664 non-null float64
STL%                 664 non-null float64
BLK%                 664 non-null float64
TOV%                 660 non-null float64
USG%                 664 non-null float64
OWS                  664 non-null float64
DWS                  664 non-null float64
WS                   664 non-null float64
WS/48                664 non-null float64
OBPM                 664 non-null float64
DBPM                 664 non-null float64
BPM                  664 non-null float64
VORP                 664 non-null float64
pct_of_FGA_twos      660 non-null float64
pct_of_FGA_threes    660 non-null float64
two_pt_fg_pct        646 non-null float64
three_pt_fg_pct      599 non-null float64
dtypes: float64(46), int64(5), object(3)
memory usage: 280.2+ KB

In [12]:
#Gathering Tracking Data from stats.nba.com via nba_tracking_stats api 
#select drives, CatchShoot, Passing, Possessions, SpeedDistance, PullUpShot

In [13]:
#preview statistics related to drives to the basket

stat_measure = 'Drives'
seasons = ['2018-19']
season_types = ['Regular Season']
entity_type = 'player'

stats, league_totals = tracking.aggregate_full_season_tracking_stats_for_seasons(
    stat_measure,
    seasons,
    season_types,
    entity_type)

    
    
pd.DataFrame(stats)

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,MIN,DRIVES,DRIVE_FGM,DRIVE_FGA,DRIVE_FTM,DRIVE_FTA,DRIVE_PTS,DRIVE_PASSES,DRIVE_AST,DRIVE_TOV,DRIVE_PF
0,203932,Aaron Gordon,1610612753,ORL,2567.0,466,88,205,58,82,243,160,48,48,40
1,1628988,Aaron Holiday,1610612754,IND,646.0,180,30,71,9,10,71,91,25,7,5
2,1627846,Abdel Nader,1610612760,OKC,686.0,130,36,71,9,14,83,42,11,9,5
3,201143,Al Horford,1610612738,BOS,1973.0,110,28,50,15,17,72,42,13,9,7
4,202329,Al-Farouq Aminu,1610612757,POR,2292.0,222,53,114,35,41,144,56,26,20,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,203897,Zach LaVine,1610612741,CHI,2130.0,841,207,417,160,197,590,247,52,60,95
526,1629155,Zach Lofton,1610612765,DET,4.0,1,0,0,0,0,0,1,0,0,0
527,2585,Zaza Pachulia,1610612765,DET,878.0,26,6,9,6,10,18,10,1,1,5
528,1629015,Zhaire Smith,1610612755,PHI,111.0,14,3,6,1,2,7,4,0,2,1
529,1627753,Zhou Qi,1610612745,HOU,1.0,0,0,0,0,0,0,0,0,0,0

In [14]:
#preview statistics related to catch and shoot attempts
stat_measure = 'CatchShoot'
seasons = ['2017-18']
season_types = ['Regular Season']
entity_type = 'player'
stats, league_totals = tracking.aggregate_full_season_tracking_stats_for_seasons(
    stat_measure,
    seasons,
    season_types,
    entity_type
)
pd.DataFrame(stats)

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,MIN,CATCH_SHOOT_FGM,CATCH_SHOOT_FGA,CATCH_SHOOT_PTS,CATCH_SHOOT_FG3M,CATCH_SHOOT_FG3A
0,201166,Aaron Brooks,1610612750,MIN,189.0,8,15,24,8.0,14.0
1,203932,Aaron Gordon,1610612753,ORL,1909.0,100,265,289,89.0,227.0
2,1626151,Aaron Harrison,1610612742,DAL,233.0,8,37,24,8.0,37.0
3,1628935,Aaron Jackson,1610612745,HOU,35.0,0,2,0,0.0,2.0
4,1627846,Abdel Nader,1610612738,BOS,522.0,23,65,68,22.0,63.0
...,...,...,...,...,...,...,...,...,...,...
535,1628380,Zach Collins,1610612757,POR,1045.0,45,137,125,35.0,109.0
536,203897,Zach LaVine,1610612741,CHI,656.0,13,40,39,13.0,40.0
537,2216,Zach Randolph,1610612758,SAC,1508.0,78,225,206,50.0,143.0
538,2585,Zaza Pachulia,1610612744,GSW,972.0,17,40,34,0.0,1.0
539,1627753,Zhou Qi,1610612745,HOU,124.0,2,19,6,2.0,19.0

In [15]:
#preview statistics related to drives to how often a player has the ball 
stat_measure = 'Possessions'
seasons = ['2018-19']
season_types = ['Regular Season']
entity_type = 'player'
stats, league_totals = tracking.aggregate_full_season_tracking_stats_for_seasons(
    stat_measure,
    seasons,
    season_types,
    entity_type
)
pd.DataFrame(stats)

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,MIN,POINTS,TOUCHES,FRONT_CT_TOUCHES,TIME_OF_POSS,ELBOW_TOUCHES,POST_TOUCHES,PAINT_TOUCHES
0,203932,Aaron Gordon,1610612753,ORL,2567.0,1230,4142,2485,180.8,198,219,328
1,1628988,Aaron Holiday,1610612754,IND,646.0,294,1149,523,78.4,9,0,6
2,1627846,Abdel Nader,1610612760,OKC,686.0,238,615,391,22.4,8,0,15
3,201143,Al Horford,1610612738,BOS,1973.0,925,3878,2542,115.3,279,254,351
4,202329,Al-Farouq Aminu,1610612757,POR,2292.0,760,2914,1365,92.6,88,21,197
...,...,...,...,...,...,...,...,...,...,...,...,...
525,203897,Zach LaVine,1610612741,CHI,2130.0,1469,3900,2257,297.1,50,28,86
526,1629155,Zach Lofton,1610612765,DET,4.0,0,5,3,0.2,0,0,0
527,2585,Zaza Pachulia,1610612765,DET,878.0,267,1417,868,43.3,166,69,236
528,1629015,Zhaire Smith,1610612755,PHI,111.0,40,121,93,3.6,4,0,6
529,1627753,Zhou Qi,1610612745,HOU,1.0,2,1,1,0.0,0,0,1

In [16]:
#preview statistics related to pull up shots
stat_measure = 'PullUpShot'
seasons = ['2018-19']
season_types = ['Regular Season']
entity_type = 'player'
stats, league_totals = tracking.aggregate_full_season_tracking_stats_for_seasons(
    stat_measure,
    seasons,
    season_types,
    entity_type
)
pd.DataFrame(stats)

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,MIN,PULL_UP_FGM,PULL_UP_FGA,PULL_UP_PTS,PULL_UP_FG3M,PULL_UP_FG3A
0,203932,Aaron Gordon,1610612753,ORL,2633.0,96,265,222,30.0,93.0
1,1628988,Aaron Holiday,1610612754,IND,646.0,44,130,106,18.0,61.0
2,1627846,Abdel Nader,1610612760,OKC,694.0,4,13,10,2.0,5.0
3,201143,Al Horford,1610612738,BOS,1973.0,22,48,44,0.0,0.0
4,202329,Al-Farouq Aminu,1610612757,POR,2292.0,7,41,16,2.0,14.0
...,...,...,...,...,...,...,...,...,...,...
525,203897,Zach LaVine,1610612741,CHI,2171.0,144,403,360,72.0,195.0
526,1629155,Zach Lofton,1610612765,DET,4.0,0,0,0,0.0,0.0
527,2585,Zaza Pachulia,1610612765,DET,878.0,4,13,8,0.0,3.0
528,1629015,Zhaire Smith,1610612755,PHI,111.0,3,8,8,2.0,4.0
529,1627753,Zhou Qi,1610612745,HOU,1.0,0,0,0,NaN,NaN

In [17]:
#preview statistics related to speed and distance traveled for each player
stat_measure = 'SpeedDistance'
seasons = ['2018-19']
season_types = ['Regular Season']
entity_type = 'player'
stats, league_totals = tracking.aggregate_full_season_tracking_stats_for_seasons(
    stat_measure,
    seasons,
    season_types,
    entity_type
)
pd.DataFrame(stats)

,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,MIN,DIST_FEET,DIST_MILES,DIST_MILES_OFF,DIST_MILES_DEF
0,203932,Aaron Gordon,1610612753,ORL,2567.0,1026628.0,194.4,109.5,84.9
1,1628988,Aaron Holiday,1610612754,IND,646.0,266857.0,50.5,26.2,24.3
2,1627846,Abdel Nader,1610612760,OKC,686.0,292756.0,55.4,28.2,27.3
3,201143,Al Horford,1610612738,BOS,1973.0,733629.0,138.9,73.8,65.2
4,202329,Al-Farouq Aminu,1610612757,POR,2292.0,915800.0,173.4,95.4,78.0
...,...,...,...,...,...,...,...,...,...
525,203897,Zach LaVine,1610612741,CHI,2130.0,881579.0,167.0,91.6,75.4
526,1629155,Zach Lofton,1610612765,DET,4.0,1474.0,0.3,0.1,0.1
527,2585,Zaza Pachulia,1610612765,DET,878.0,335080.0,63.5,34.6,28.8
528,1629015,Zhaire Smith,1610612755,PHI,111.0,47651.0,9.0,5.0,4.0
529,1627753,Zhou Qi,1610612745,HOU,1.0,385.0,0.1,0.0,0.0

In [18]:
def create_tracking_dataframes(season_type, year, entity):
    
    """This function uses the NBA Tracking API to collect various tracking data and combines the data
    into a single dataframe. This function collects information from the following tracking statistics:
    
    -Drives
    -Catch and Shoot
    -Possessions
    -Pull Up Shots
    -Speed and Distance
    
    Documentation on the API can be found at:
    
    https://nba-stats-tracking.readthedocs.io/en/latest/source/quickstart.html#
    
    season_type: Can be Regular Season or Playoffs. Needs to be a string.
    
    year: The year for which tracking data will be collected. Should be a string formatted
    like XXXX-XX (i.e. 2017-18).
    
    entity_type: Whether you would like to look at team or player statistics. Should be a string."""
    
    stats_to_track = ['Drives', 'CatchShoot', 'Possessions', 'PullUpShot', 'SpeedDistance']
    
    tracking_stats_list = []
    
    for stat in stats_to_track:
        measurable, league_stats = tracking.aggregate_full_season_tracking_stats_for_seasons(
            stat, #type of tracking data to collect
            [year], #specific season 
            [season_type], #regular season stats will be collected
            entity #player statistics will be collected
        ) 
        
        tracking_stats_list.append(measurable)
        time.sleep(3)
    
    #Create a dataframe for each type of stat
    drives_df = pd.DataFrame(tracking_stats_list[0])       #Drives to the basket
    catch_shoot_df = pd.DataFrame(tracking_stats_list[1])  #Catch and shoot
    poss_df = pd.DataFrame(tracking_stats_list[2])         #Number of touches
    pullup_df = pd.DataFrame(tracking_stats_list[3])       #Pull Up Shots
    speed_dist_df = pd.DataFrame(tracking_stats_list[4])   #Speed and Distance Metrics
    
    #Create a new dataframe combining pertinent columns from each type of tracking statistic
    tracking_combined_df = pd.DataFrame([])
    
    #select columns from drives_df
    if entity_type == 'player':
        tracking_combined_df['PLAYER_ID'] = drives_df['PLAYER_ID']
        tracking_combined_df['PLAYER_NAME'] = drives_df['PLAYER_NAME']
        
    tracking_combined_df['TEAM_ID'] = drives_df['TEAM_ID']
    tracking_combined_df['TEAM_ABBR'] = drives_df['TEAM_ABBREVIATION']
    tracking_combined_df['DRIVES'] = drives_df['DRIVES']
    tracking_combined_df['DRIVE_FGM'] = drives_df['DRIVE_FGM']
    tracking_combined_df['DRIVE_FGA'] = drives_df['DRIVE_FGA']
    tracking_combined_df['DRIVE_PASSES'] = drives_df['DRIVE_PASSES']
    
    #select columns from catch_shoot_df
    tracking_combined_df['CATCH_SHOOT_FGM'] = catch_shoot_df['CATCH_SHOOT_FGM']
    tracking_combined_df['CATCH_SHOOT_FGA'] = catch_shoot_df['CATCH_SHOOT_FGA']
    tracking_combined_df['CATCH_SHOOT_FG3M'] = catch_shoot_df['CATCH_SHOOT_FG3M']
    tracking_combined_df['CATCH_SHOOT_FG3A'] = catch_shoot_df['CATCH_SHOOT_FG3A']
    
    #select columns from catch poss_df
    tracking_combined_df['TOUCHES'] = poss_df['TOUCHES']
    tracking_combined_df['FRONT_CT_TOUCHES'] = poss_df['FRONT_CT_TOUCHES']
    tracking_combined_df['TIME_OF_POSS'] = poss_df['TIME_OF_POSS']
    
    #select columns from pullup_df
    tracking_combined_df['PULL_UP_FGM'] = pullup_df['PULL_UP_FGM']
    tracking_combined_df['PULL_UP_FGA'] = pullup_df['PULL_UP_FGA']
    tracking_combined_df['PULL_UP_FG3M'] = pullup_df['PULL_UP_FG3M']
    tracking_combined_df['PULL_UP_FG3A'] = pullup_df['PULL_UP_FG3A']
    
    #select columns from speed_dist_df
    tracking_combined_df['DIST_MILES'] = speed_dist_df['DIST_MILES']
    tracking_combined_df['DIST_MILES_OFF'] = speed_dist_df['DIST_MILES_OFF']
    tracking_combined_df['DIST_MILES_DEF'] = speed_dist_df['DIST_MILES_DEF']
    
    return tracking_combined_df

In [19]:
nbatrack_17_18 = create_tracking_dataframes('Regular Season', '2017-18', 'player')
nbatrack_17_18
nbatrack_17_18.loc[nbatrack_17_18['PLAYER_NAME'] == 'Juancho Hernangomez', 'PLAYER_NAME'] = 'Juan Hernangomez'
nbatrack_17_18.loc[nbatrack_17_18['PLAYER_NAME'] == 'Vincent Hunter', 'PLAYER_NAME'] = 'Vince Hunter'
nbatrack_17_18.loc[nbatrack_17_18['PLAYER_NAME'] == 'Wes Iwundu', 'PLAYER_NAME'] = 'Wesley Iwundu'

In [20]:
import unidecode
#We'll use this module to convert letters with accents or other special characters on letters

In [21]:
string = bballref_1718_df.iloc[263]['Player'] 
string

'Nenê\\hilarne01'

In [22]:
unidecode.unidecode(string.split('\\')[0]).split()

['Nene']

In [23]:
def clean_names(name):
    """This function removes extraneous player IDs from player names collected from Basketball Reference.
       The function removes punctuation from names as name punction is not consistent across different
       sources. The function also removes suffixes from names as suffixes are not consistent across different
       sources. 
       
       The function takes a variable 'name' which should be a string."""
    
    #Name from Basketball Reference will follow the logic in the first if statement
    
    if '\\' in name:
        name_new = name.split('\\')[0]
        if '.' or '*' in name_new:
            name_stripped = name_new.replace('.', '').replace('*', '') #remove punctuation
        else:
            name_stripped = name_new
    
    #Names from stats.nba.com will follow the logic in the unnested else statement
    
    else:
        name_new = name
        if '.' in name_new:
            name_stripped = name_new.replace('.', '') #remove punctuation
        else:
            name_stripped = name_new
    

    
    name_clean = unidecode.unidecode(name_stripped) #remove accents and special characters
    
    name_split = name_clean.split() #split into first name, last name, and suffix if applicable
    
    if len(name_split) < 2:
        name_final = name_split[0]
    
    else:
        name_final = name_split[0] + ' ' + name_split[1] #store only first and last names in variable
    
    return name_final

In [24]:
clean_names(string)

'Nene'

In [25]:
def join_nba_sources(dataframe1, dataframe2, year):
    """This function joins dataframes created from Basketball Reference and stats.nba.com so each player has
    box score, advanced, and tracking statistics.
    
    dataframe1: Dataframe from Basketball Reference.
    
    dataframe2: Dataframe from stats.nba.com
    
    year: The season that corresponds with the two dataframes. Should be a string.
    
    Both dataframes should be the same length (i.e. contain the same listing of players.)"""
    
    df_bball_ref = dataframe1
    df_nba_track = dataframe2
    
    df_bball_ref['Player'] = df_bball_ref['Player'].map(clean_names)
    df_nba_track['PLAYER_NAME'] = df_nba_track['PLAYER_NAME'].map(clean_names)
    
    df_bball_ref.drop_duplicates(subset=['Player'], keep='first', inplace=True)
    df_nba_track.drop_duplicates(subset=['PLAYER_ID'], keep='first', inplace=True)
    
    df_nba_track.drop(columns=['PLAYER_ID', 'TEAM_ID', 'TEAM_ABBR'], inplace=True)
    
    df_bball_ref.rename(columns={'Player':'PLAYER_NAME'}, inplace=True)
    
    df_bball_ref.set_index('PLAYER_NAME', inplace=True)
    df_nba_track.set_index('PLAYER_NAME', inplace=True)
    
    if len(dataframe1) != len(dataframe2):
        return print('Error: Dataframes not the same length.')
    else:
        df_final = df_bball_ref.join(df_nba_track, how='left')
        df_final.reset_index(inplace=True)
        df_final['PLAYER_NAME'] = df_final['PLAYER_NAME'].map(lambda x: x + ' ' + f'({year})' )
        return df_final

In [26]:
nba_df_1718 = join_nba_sources(bballref_1718_df, nbatrack_17_18, '17-18')

In [27]:
nba_df_1718.head()

,PLAYER_NAME,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,TOUCHES,FRONT_CT_TOUCHES,TIME_OF_POSS,PULL_UP_FGM,PULL_UP_FGA,PULL_UP_FG3M,PULL_UP_FG3A,DIST_MILES,DIST_MILES_OFF,DIST_MILES_DEF
0,Alex Abrines (17-18),SG,24,OKC,75,8,1134,5.0,12.7,0.395,...,1093,694,35.0,6,21,1.0,11.0,80.0,40.3,39.7
1,Quincy Acy (17-18),PF,27,BRK,70,8,1359,4.6,13.0,0.356,...,2228,1358,47.2,5,15,2.0,7.0,91.4,50.8,40.6
2,Steven Adams (17-18),C,24,OKC,76,76,2487,8.9,14.2,0.629,...,2998,1950,70.3,1,10,0.0,1.0,167.3,82.7,84.6
3,Bam Adebayo (17-18),C,20,MIA,69,19,1368,6.4,12.5,0.512,...,1856,1366,66.7,2,12,0.0,3.0,92.5,48.3,44.1
4,Arron Afflalo (17-18),SG,32,ORL,53,3,682,4.7,11.6,0.401,...,746,580,25.3,21,52,2.0,10.0,47.5,25.0,22.5

In [28]:
nbatrack_15_16 = create_tracking_dataframes('Regular Season', '2015-16', 'player')

df4 = pd.read_csv('2015-2016_player_per100poss.csv')
df5 = pd.read_csv('2015-2016_players_adv.csv')
df6 = pd.read_csv('2015-2016_player_shooting_stats.csv', header = [0, 1])

bballref_1516_df = join_dataframes(df4, df5, df6)

nba_df_1516 = join_nba_sources(bballref_1516_df, nbatrack_15_16, '15-16')

In [29]:
nbatrack_16_17 = create_tracking_dataframes('Regular Season', '2016-17', 'player')
nbatrack_16_17.loc[nbatrack_16_17['PLAYER_NAME'] == 'Juancho Hernangomez', 'PLAYER_NAME'] = 'Juan Hernangomez'


df7 = pd.read_csv('2016-2017_player_per100poss.csv')
df8 = pd.read_csv('2016-2017_players_adv.csv')
df9 = pd.read_csv('2016-2017_player_shooting_stats.csv', header = [0, 1])

bballref_1617_df = join_dataframes(df7, df8, df9)

nba_df_1617 = join_nba_sources(bballref_1617_df, nbatrack_16_17, '16-17')

In [30]:
nbatrack_18_19 = create_tracking_dataframes('Regular Season', '2018-19', 'player')
nbatrack_18_19.loc[nbatrack_18_19['PLAYER_NAME'] == 'Juancho Hernangomez', 'PLAYER_NAME'] = 'Juan Hernangomez'
nbatrack_18_19.loc[nbatrack_18_19['PLAYER_NAME'] == 'Mitchell Creek', 'PLAYER_NAME'] = 'Mitch Creek'
nbatrack_18_19.loc[nbatrack_18_19['PLAYER_NAME'] == 'Vincent Edwards', 'PLAYER_NAME'] = 'Vince Edwards'
nbatrack_18_19.loc[nbatrack_18_19['PLAYER_NAME'] == 'Wes Iwundu', 'PLAYER_NAME'] = 'Wesley Iwundu'
nbatrack_18_19.loc[nbatrack_18_19['PLAYER_NAME'] == 'Svi Mykhailiuk', 'PLAYER_NAME'] = 'Sviatoslav Mykhailiuk' 

df10 = pd.read_csv('2018-2019_player_per100poss.csv')
df11 = pd.read_csv('2018-2019_player_adv.csv')
df12 = pd.read_csv('2018-2019_player_shooting_stats.csv', header = [0, 1])

bballref_1819_df = join_dataframes(df10, df11, df12)

nba_df_1819 = join_nba_sources(bballref_1819_df, nbatrack_18_19, '18-19')

In [31]:
nba_df_1516.head()

,PLAYER_NAME,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,TOUCHES,FRONT_CT_TOUCHES,TIME_OF_POSS,PULL_UP_FGM,PULL_UP_FGA,PULL_UP_FG3M,PULL_UP_FG3A,DIST_MILES,DIST_MILES_OFF,DIST_MILES_DEF
0,Quincy Acy (15-16),PF,25,SAC,59,29,876,6.5,11.7,0.556,...,1116,602,23.3,5,10,2.0,2.0,62.4,32.3,30.1
1,Jordan Adams (15-16),SG,21,MEM,2,0,15,6.9,20.6,0.333,...,22,12,0.8,1,3,0.0,0.0,1.2,0.6,0.5
2,Steven Adams (15-16),C,22,OKC,80,80,2014,6.4,10.5,0.613,...,3601,1421,81.9,0,2,NaN,NaN,143.0,77.2,65.8
3,Arron Afflalo (15-16),SG,30,NYK,71,57,2371,7.7,17.3,0.443,...,3744,2749,157.5,132,292,12.0,37.0,165.9,92.4,73.5
4,Alexis Ajinca (15-16),C,27,NOP,59,17,861,8.6,18.1,0.476,...,1485,773,34.7,10,21,0.0,0.0,58.3,30.4,27.9

In [32]:
nba_df_1617.head()

,PLAYER_NAME,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,TOUCHES,FRONT_CT_TOUCHES,TIME_OF_POSS,PULL_UP_FGM,PULL_UP_FGA,PULL_UP_FG3M,PULL_UP_FG3A,DIST_MILES,DIST_MILES_OFF,DIST_MILES_DEF
0,Alex Abrines (16-17),SG,23,OKC,68,6,1055,6.2,15.9,0.393,...,1262,916,35.2,13,48,5.0,24.0,76.4,40.6,35.9
1,Quincy Acy (16-17),PF,26,TOT,38,1,558,6.0,14.6,0.412,...,888,545,20.2,6,18,1.0,3.0,39.0,21.1,17.9
2,Steven Adams (16-17),C,23,OKC,80,80,2389,7.7,13.5,0.571,...,2866,1841,77.5,3,18,0.0,0.0,162.4,82.2,80.2
3,Arron Afflalo (16-17),SG,31,SAC,61,45,1580,5.9,13.5,0.440,...,2081,1555,81.1,57,132,5.0,15.0,107.4,59.4,48.1
4,Alexis Ajinca (16-17),C,28,NOP,39,15,584,7.5,14.9,0.500,...,956,467,21.4,6,9,0.0,0.0,40.7,21.6,19.1

In [33]:
nba_df_1819.head()

,PLAYER_NAME,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,TOUCHES,FRONT_CT_TOUCHES,TIME_OF_POSS,PULL_UP_FGM,PULL_UP_FGA,PULL_UP_FG3M,PULL_UP_FG3A,DIST_MILES,DIST_MILES_OFF,DIST_MILES_DEF
0,Alex Abrines (18-19),SG,25,OKC,31,2,588,4.4,12.5,0.357,...,514,384,16.2,8,16,6.0,11.0,46.4,24.1,22.3
1,Quincy Acy (18-19),PF,28,PHO,10,0,123,1.6,7.0,0.222,...,197,101,4.2,0,0,0.0,0.0,9.4,5.1,4.2
2,Jaylen Adams (18-19),PG,22,ATL,34,1,428,4.1,11.9,0.345,...,941,278,73.7,13,40,8.0,26.0,33.9,18.2,15.7
3,Steven Adams (18-19),C,25,OKC,80,80,2669,8.4,14.1,0.595,...,3555,1991,100.0,7,15,0.0,0.0,191.3,93.9,97.4
4,Bam Adebayo (18-19),C,21,MIA,82,28,1913,7.2,12.4,0.576,...,2830,1823,98.2,17,35,2.0,4.0,141.0,75.5,65.5

In [34]:
nba_df_15_19 = pd.concat([nba_df_1516, nba_df_1617, nba_df_1718, nba_df_1819], ignore_index=True)
nba_df_15_19.head()

,PLAYER_NAME,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,TOUCHES,FRONT_CT_TOUCHES,TIME_OF_POSS,PULL_UP_FGM,PULL_UP_FGA,PULL_UP_FG3M,PULL_UP_FG3A,DIST_MILES,DIST_MILES_OFF,DIST_MILES_DEF
0,Quincy Acy (15-16),PF,25,SAC,59,29,876,6.5,11.7,0.556,...,1116,602,23.3,5,10,2.0,2.0,62.4,32.3,30.1
1,Jordan Adams (15-16),SG,21,MEM,2,0,15,6.9,20.6,0.333,...,22,12,0.8,1,3,0.0,0.0,1.2,0.6,0.5
2,Steven Adams (15-16),C,22,OKC,80,80,2014,6.4,10.5,0.613,...,3601,1421,81.9,0,2,NaN,NaN,143.0,77.2,65.8
3,Arron Afflalo (15-16),SG,30,NYK,71,57,2371,7.7,17.3,0.443,...,3744,2749,157.5,132,292,12.0,37.0,165.9,92.4,73.5
4,Alexis Ajinca (15-16),C,27,NOP,59,17,861,8.6,18.1,0.476,...,1485,773,34.7,10,21,0.0,0.0,58.3,30.4,27.9

In [35]:
nba_df_15_19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2032 entries, 0 to 2031
Data columns (total 72 columns):
PLAYER_NAME          2032 non-null object
Pos                  2032 non-null object
Age                  2032 non-null int64
Tm                   2032 non-null object
G                    2032 non-null int64
GS                   2032 non-null int64
MP                   2032 non-null int64
FG                   2032 non-null float64
FGA                  2032 non-null float64
FG%                  2023 non-null float64
3P                   2032 non-null float64
3PA                  2032 non-null float64
3P%                  1868 non-null float64
2P                   2032 non-null float64
2PA                  2032 non-null float64
2P%                  2004 non-null float64
FT                   2032 non-null float64
FTA                  2032 non-null float64
FT%                  1937 non-null float64
ORB                  2032 non-null float64
DRB                  2032 non-null float64
TRB                  2032 non-null float64
AST                  2032 non-null float64
STL                  2032 non-null float64
BLK                  2032 non-null float64
TOV                  2032 non-null float64
PF                   2032 non-null float64
PTS                  2032 non-null float64
ORtg                 2024 non-null float64
DRtg                 2032 non-null int64
PER                  2032 non-null float64
TS%                  2023 non-null float64
3PAr                 2023 non-null float64
FTr                  2023 non-null float64
ORB%                 2032 non-null float64
DRB%                 2032 non-null float64
TRB%                 2032 non-null float64
AST%                 2032 non-null float64
STL%                 2032 non-null float64
BLK%                 2032 non-null float64
TOV%                 2023 non-null float64
USG%                 2032 non-null float64
OWS                  2032 non-null float64
DWS                  2032 non-null float64
WS                   2032 non-null float64
WS/48                2032 non-null float64
OBPM                 2032 non-null float64
DBPM                 2032 non-null float64
BPM                  2032 non-null float64
VORP                 2032 non-null float64
pct_of_FGA_twos      2023 non-null float64
pct_of_FGA_threes    2023 non-null float64
two_pt_fg_pct        2004 non-null float64
three_pt_fg_pct      1868 non-null float64
DRIVES               2032 non-null int64
DRIVE_FGM            2032 non-null int64
DRIVE_FGA            2032 non-null int64
DRIVE_PASSES         2032 non-null int64
CATCH_SHOOT_FGM      2032 non-null int64
CATCH_SHOOT_FGA      2032 non-null int64
CATCH_SHOOT_FG3M     1866 non-null float64
CATCH_SHOOT_FG3A     1866 non-null float64
TOUCHES              2032 non-null int64
FRONT_CT_TOUCHES     2032 non-null int64
TIME_OF_POSS         2032 non-null float64
PULL_UP_FGM          2032 non-null int64
PULL_UP_FGA          2032 non-null int64
PULL_UP_FG3M         1866 non-null float64
PULL_UP_FG3A         1866 non-null float64
DIST_MILES           2031 non-null float64
DIST_MILES_OFF       2031 non-null float64
DIST_MILES_DEF       2031 non-null float64
dtypes: float64(54), int64(15), object(3)
memory usage: 1.1+ MB

In [36]:
nba_df_15_19.to_csv('nba_complete_2015-2019.csv', index=False)